ec-jrc/re3gistry

- documentation/administrator-manual.md
- documentation/developer-manual.md
- documentation/user-manual.md
Fix some typos in the documentation.
> Fix several typos in documentation

- documentation/administrator-manual.md
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/LoadSalt.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ValidateSalt.java
> Improve description of installation process, improve ValidateSalt

- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Install.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/Configuration.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/Initializer.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/InitializerLight.java
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/solr/SolrHandler.java
> Update the handling of the helper files (system.installed, ...)

- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/util/DateUtil.java
> Update DateUtil so it is not locale-dependent

- sources/Re3gistry2-build-helper/pom.xml
- sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties
Properties in configuration.properties in Re3gistry2:
- ~application.status.baseuri~
- SMTP properties, including user and password
- sender mail address for mails
Also fix 2 errors related to application.rooturl.
> Make it possible to set more properties using Maven build profiles

- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/ItemsServlet.java
> Remove code that modifies requested URI

- documentation/administrator-manual.md
- It is important to highlight that the Java version should be exact 1.8.
- It is important to give more info regarding the Tomcat versions
> Update administrator manual regarding requirements

- sources/Re3gistry2ServiceWebapp/public_html/js-ecl-v2/app_i18n.js
Change default language to english if browser language not active #238
> #238 Change default language

- sources/Re3gistry2Migration/src/main/java/eu/europa/ec/re3gistry2/migration/handler/RegInstallationStepMigrationPorcessHandler.java
- sources/Re3gistry2Migration/src/main/java/eu/europa/ec/re3gistry2/migration/manager/MigrateItemHistory.java
- sources/Re3gistry2Migration/src/main/java/eu/europa/ec/re3gistry2/migration/manager/MigrateItemLatestVersion.java
- sources/Re3gistry2Migration/src/main/java/eu/europa/ec/re3gistry2/migration/manager/MigrateItems.java
- sources/Re3gistry2Migration/src/main/java/eu/europa/ec/re3gistry2/migration/manager/MigrationManager.java
Includes solutions for issues #218 and #68
> #218 Migration process errors

- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsers.java
- sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties
- sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties.orig
- sources/Re3gistry2/src/main/resources/localizations/LocalizationBundle_en.properties
- sources/Re3gistry2/src/main/webapp/jsp/registryManagerUsers.jsp
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/BaseConstants.java
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegUserHandler.java
- sources/Re3gistry2ServiceWebapp/public_html/js-ecl-v2/app_core.js
> 201 email when roles changed

- dist/db-scripts/registry2_drop-and-create-and-init.sql.orig
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Activate.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsersAdd.java
- sources/Re3gistry2/src/main/resources/META-INF/persistence.xml
- sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties
- sources/Re3gistry2/src/main/resources/localizations/LocalizationBundle_en.properties
- sources/Re3gistry2/src/main/resources/shiro.ini
- sources/Re3gistry2/src/main/webapp/jsp/activate.jsp
- sources/Re3gistry2/src/main/webapp/jsp/registryManagerUsers.jsp
- sources/Re3gistry2/src/main/webapp/jsp/userDeleted.jsp
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/BaseConstants.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/Configuration.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/Initializer.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/UserCodesJob.java
- sources/Re3gistry2Base/src/main/java/eu/europa/ec/re3gistry2/base/utility/WebConstants.java
- sources/Re3gistry2CRUDinterface/src/main/java/eu/europa/ec/re3gistry2/crudinterface/IRegUserCodesManager.java
- sources/Re3gistry2CRUDinterface/src/main/java/eu/europa/ec/re3gistry2/crudinterface/IRegUserManager.java
- sources/Re3gistry2CRUDrdb/src/main/java/eu/europa/ec/re3gistry2/crudimplementation/RegUserCodesManager.java
- sources/Re3gistry2CRUDrdb/src/main/java/eu/europa/ec/re3gistry2/crudimplementation/RegUserManager.java
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegUserHandler.java
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegUserRegCodesHandler.java
- sources/Re3gistry2Model/src/main/java/eu/europa/ec/re3gistry2/model/RegUserCodes.java
- sources/Re3gistry2Model/src/main/java/eu/europa/ec/re3gistry2/model/utility/RandomStringUtils.java
- sources/Re3gistry2Model/src/main/java/eu/europa/ec/re3gistry2/model/uuidhandlers/RegUserCodesUuidHelper.java
- sources/Re3gistry2RestAPI/src/main/resources/META-INF/persistence.xml
> Adding a user to the platform let them accept if he/she agrees to join

- scripts/index.sql
I created a new SQL script in order to optimize the Postgres DB queries adding indexes on some tables.
We tested the same queries with the indexes applied and the performance has definitely improved.
> Added script to optimize DB queries

- apache_conf/httpd.conf
- scripts/index.sql
This Apaxche configuration file contains the module that provides the DEFLATE output filter that allows output from your server to be compressed before being sent to the client over the network.
> Apache http compression

- README.md
According to releases https://github.com/ec-jrc/re3gistry/releases the latest is 2.5.1
> Update latest version on README

- sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties
- sources/Re3gistry2/src/main/resources/localizations/LocalizationBundle_en.properties
- sources/Re3gistry2/src/main/webapp/jsp/includes/footer.inc.jsp
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegBulkImportHandler.java
- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegItemproposedHandler.java
> Release v2.5.2

- sources/Re3gistry2/src/main/webapp/jsp/addItemclass.jsp
Deleted unnecessary error message in addItem.jsp
> #414 Deleted unnecessary error message

- dist/app/re3gistry2/WEB-INF/classes/configurations_files/configuration.properties
> 2.6.0 release

- sources/Re3gistry2ServiceWebapp/public_html/conf/conf.js
- sources/Re3gistry2ServiceWebapp/public_html/index.html
- sources/Re3gistry2ServiceWebapp/public_html/js-ecl-v2/app_i18n.js
Builds on https://github.com/ec-jrc/re3gistry/pull/360 to fix paths to `icons.svg` as well.
> Fix paths for static files

- sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/cache/supplier/ItemSupplier.java
Merge into develop - Issue #428
> #428 Added validation

- dist/app/re3gistry2/WEB-INF/classes/configurations_files/configuration.properties
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ActionDetail.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/AddItem.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/AddRegister.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Browse.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/BulkImport.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ControlBody.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/DiscardProposal.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Field.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Install.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ItemChildrenListLoaderServlet.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ItemListLoaderServlet.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/MapField.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegisterManager.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManager.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerDataExport.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerGroups.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerGroupsAdd.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsers.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsersAdd.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/UserProfile.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/utility/jsp/JspHelper.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/utility/jsp/JspHelperNewProposedItem.java
- sources/Re3gistry2/src/main/webapp/jsp/content.jsp
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/ATOMFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/JSONFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/RORFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/XSDFormatter.java
Add Issue 444 solution to develop branch
> 444 improve error logs and messages

- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ActionDetail.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/AddItem.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/AddRegister.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Browse.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/BulkImport.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ControlBody.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/DiscardProposal.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Field.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/Install.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ItemChildrenListLoaderServlet.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/ItemListLoaderServlet.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/MapField.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegisterManager.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManager.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerDataExport.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerGroups.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerGroupsAdd.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsers.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/RegistryManagerUsersAdd.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/controller/UserProfile.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/utility/jsp/JspHelper.java
- sources/Re3gistry2/src/main/java/eu/europa/ec/re3gistry2/web/utility/jsp/JspHelperNewProposedItem.java
- sources/Re3gistry2/src/main/webapp/jsp/content.jsp
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/ATOMFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/JSONFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/RORFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/XMLFormatter.java
- sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/XSDFormatter.java
This reverts commit 773c1cb738364a29d8e4a2b36b711414cc24ca21.
> Reapply "444 improve error logs and messages"

- release-strategy/README.md
Revised release planning strategy for 2025 and 2026.
> Draft release strategy
